/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsyncComponent: typeof import('./components/AsyncComponent.vue')['default']
    CardComp: typeof import('./components/CardComp.vue')['default']
    DynamicComp1: typeof import('./components/Dynamic/DynamicComp1.vue')['default']
    DynamicComp2: typeof import('./components/Dynamic/DynamicComp2.vue')['default']
    DynamicComp3: typeof import('./components/Dynamic/DynamicComp3.vue')['default']
    EditComp: typeof import('./components/EditComp.vue')['default']
    InjectComp: typeof import('./components/InjectComp.vue')['default']
    KeepAliveComp: typeof import('./components/KeepAliveComp.vue')['default']
    MenuComp: typeof import('./components/MenuComp.vue')['default']
    ModelComp: typeof import('./components/ModelComp.vue')['default']
    MyTree: typeof import('./components/MyTree.vue')['default']
    ProvideComp: typeof import('./components/ProvideComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowComp: typeof import('./components/ShowComp.vue')['default']
    SlotComp: typeof import('./components/SlotComp.vue')['default']
    WaterFall: typeof import('./components/WaterFall.vue')['default']
  }
}
